
image:
  name: ubuntu:latest

variables:
  BUILDBEN_HOST_URL: "<insert value here>"
  BUILDBEN_AGENT_URL: "<insert value here>"
  BUILDBEN_S3_REGION: "<insert value here>"
  BUILDBEN_S3_BUCKET_NAME: "<insert value here>"
  BUILDBEN_S3_ACCESS_KEY_ID: "<insert value here>"
  BUILDBEN_S3_SECRET_ACCESS_KEY: "<insert value here>"
  BUILDBEN_MINIO_URL: "<insert value here>"
  BUILDBEN_SKIP_UNITS: "<insert value here>"

default:
  before_script:
    - apt update && apt upgrade
    - apt install curl -yq
  after_script:
    - ls -la
  tags:
    - ci

stages:
  - init
  - compile
  - compile and test

download buildben:
  stage: init
  script:
    - ls -la
    - curl $BUILDBEN_AGENT_URL -o buildben
    - chmod +x buildben
  artifacts:
    paths:
      - buildben
    expire_in: 10 mins

mvn compile:
  stage: compile
  script:
    - BUILDBEN_HOST_URL=$BUILDBEN_HOST_URL BUILDBEN_S3_BUCKET_NAME=$BUILDBEN_S3_BUCKET_NAME BUILDBEN_MINIO_URL=$BUILDBEN_MINIO_URL BUILDBEN_S3_SECRET_ACCESS_KEY=$BUILDBEN_S3_SECRET_ACCESS_KEY BUILDBEN_S3_ACCESS_KEY_ID=$BUILDBEN_S3_ACCESS_KEY_ID BUILDBEN_S3_REGION=$BUILDBEN_S3_REGION ./buildben mvn compile --settings settings.xml -Dmaven.javadoc.skip=true

mvn test-compile:
  stage: compile and test
  script:
    - BUILDBEN_HOST_URL=$BUILDBEN_HOST_URL BUILDBEN_S3_BUCKET_NAME=$BUILDBEN_S3_BUCKET_NAME BUILDBEN_MINIO_URL=$BUILDBEN_MINIO_URL BUILDBEN_S3_SECRET_ACCESS_KEY=$BUILDBEN_S3_SECRET_ACCESS_KEY BUILDBEN_S3_ACCESS_KEY_ID=$BUILDBEN_S3_ACCESS_KEY_ID BUILDBEN_S3_REGION=$BUILDBEN_S3_REGION ./buildben mvn test-compile --settings settings.xml -Dmaven.javadoc.skip=true
    - BUILDBEN_SKIP_UNITS=$BUILDBEN_SKIP_UNITS BUILDBEN_HOST_URL=$BUILDBEN_HOST_URL BUILDBEN_S3_BUCKET_NAME=$BUILDBEN_S3_BUCKET_NAME BUILDBEN_MINIO_URL=$BUILDBEN_MINIO_URL BUILDBEN_S3_SECRET_ACCESS_KEY=$BUILDBEN_S3_SECRET_ACCESS_KEY BUILDBEN_S3_ACCESS_KEY_ID=$BUILDBEN_S3_ACCESS_KEY_ID BUILDBEN_S3_REGION=$BUILDBEN_S3_REGION ./buildben mvn surefire:test --settings settings.xml
